### ISSUE TITLE
Hi! where is the pre-trained models .pth file ,i can't find it,thanks

### ISSUE THREAD

**Issue by 2zhujia** [jyicu/CBSN#2]

**Comment by jyicu** [comment]
Hi 2zhujia
We provide the pre-trained models in the form of .ckpt files located in the pretrained folder. 
You can load the checkpoint using saver.restore(./pretrained/CBSN_SIDDtrain.ckpt).
For more details on loading the pre-trained model, please refer to the infer.py script.

Best regards,
jyicu
